config:
  url: "https://api.openweathermap.org/data/2.5/weather"
  iconUrl: "http://openweathermap.org/img/wn/"
  appid: "93836445ebca1a81c1081e8b9fa753f0"
  soapNamespace: "http://task.example.com"
  good-status: OK,NOT_ACCEPTABLE
  correlationID: "client1"

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
#      quartz:
#        job-store-type: jdbc
#        properties:
#          org:
#            quartz:
#              threadPool:
#                threadCount: '5'
#
#  mail:
#    port: '587'
#    properties:
#      mail:
#        smtp:
#          auth: 'true'
#          starttls:
#            enable: 'true'
#    host: smtp.gmail.com
#    username: wojcikowski1@gmail.com
#    password: ''
#  datasource:
#    username: ''
#    url: ''
#    password: ''

  jpa:
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.SQLServerDialect
      hibernate.hbm2ddl.auto: update
      hibernate.database: MIFID_DEV4

  datasource:
    url: jdbc:sqlserver://localhost:1433;encrypt=true;trustServerCertificate=true;
    username: MIFID_DEV4
    password: Borutta666
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver




server:
  port : 8080